version: '3'

vars:
  BINARY_NAME: 'adbcon{{exeExt}}'
  COVERAGE_FILE: coverage.out

tasks:
  default:
    desc: show task list
    cmds:
      - task --list

  build:
    desc: build application
    sources:
      - '**/*.go'
    generates:
      - '{{.BINARY_NAME}}'
    cmds:
      - go build -o {{.BINARY_NAME}} ./main.go

  test:
    desc: testing.
    cmds:
      - go test -v ./...

  coverage:
    desc: make coverage report
    cmds:
      - go test -coverprofile={{.COVERAGE_FILE}} ./...
      - go tool cover -func={{.COVERAGE_FILE}}
    sources:
      - '**/*.go'
    generates:
      - '{{.COVERAGE_FILE}}'

  coverage:html:
    desc: show coverage report on browser
    deps:
      - coverage
    cmds:
      - go tool cover -html={{.COVERAGE_FILE}}

  apigen:
    desc: generate Echo server code from Open API definition
    sources:
      - openapi.yaml
    cmds:
      - go tool oapi-codegen -config ./api/config.yaml ./api/openapi.yaml

  clean:
    desc: clean artifacts
    cmds:
      - rm -f {{.BINARY_NAME}} {{.COVERAGE_FILE}}