// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerUrlDefault defines the Server URL for default
const ServerUrlDefault = "https://localhost:8080"

// Defines values for DeviceStatus.
const (
	Offline      DeviceStatus = "offline"
	Online       DeviceStatus = "online"
	Unauthorized DeviceStatus = "unauthorized"
	Unknown      DeviceStatus = "unknown"
)

// Valid indicates whether the value is a known member of the DeviceStatus enum.
func (e DeviceStatus) Valid() bool {
	switch e {
	case Offline:
		return true
	case Online:
		return true
	case Unauthorized:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for RebootArgs.
const (
	Bootloader         RebootArgs = "bootloader"
	Recovery           RebootArgs = "recovery"
	Sideload           RebootArgs = "sideload"
	SideloadAutoReboot RebootArgs = "sideload-auto-reboot"
)

// Valid indicates whether the value is a known member of the RebootArgs enum.
func (e RebootArgs) Valid() bool {
	switch e {
	case Bootloader:
		return true
	case Recovery:
		return true
	case Sideload:
		return true
	case SideloadAutoReboot:
		return true
	default:
		return false
	}
}

// CommandArgs Command arguments.
type CommandArgs = []string

// CommandResult Command result with serial.
type CommandResult struct {
	// Result Example: PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
	Result string `json:"result"`

	// Serial serial of device.
	//
	// Example: ABC123DEF
	Serial DeviceSerial `json:"serial"`
}

// CommandResults List of command results.
type CommandResults = []CommandResult

// DeviceInfo Devide information.
type DeviceInfo struct {
	// Device Example: ???
	Device *string `json:"device,omitempty"`

	// Model Model name of device.
	//
	// Example: Pixel-10
	Model *string `json:"model,omitempty"`

	// Product Product name of device.
	//
	// Example: ???
	Product *string `json:"product,omitempty"`

	// Serial serial of device.
	//
	// Example: ABC123DEF
	Serial DeviceSerial `json:"serial"`

	// Status Status of device.
	//
	// Example: online
	Status DeviceStatus `json:"status"`

	// Tid Transport ID.
	//
	// Example: 1
	Tid *int `json:"tid,omitempty"`
}

// DeviceList List of devices with information.
type DeviceList = []DeviceInfo

// DeviceSerial serial of device.
//
// Example: ABC123DEF
type DeviceSerial = string

// DeviceStatus Status of device.
//
// Example: online
type DeviceStatus string

// ProblemDetails Details for error response.
type ProblemDetails struct {
	// Detail Error message.
	//
	// Example: 'foo' is not recognized as an internal or external command, operable program or batch file.
	Detail *string `json:"detail,omitempty"`

	// Status Status code.
	//
	// Example: 500
	Status *int `json:"status,omitempty"`

	// Title Readful text for status code.
	//
	// Example: Internal Server Error
	Title *string `json:"title,omitempty"`
}

// RebootArgs argument list for adb reboot.
type RebootArgs string

// SerialList List of device serial.
type SerialList = []DeviceSerial

// PollingInterval defines model for PollingInterval.
type PollingInterval = int

// TargetList List of device serial.
type TargetList = SerialList

// ExecuteAdbLogcatParams defines parameters for ExecuteAdbLogcat.
type ExecuteAdbLogcatParams struct {
	// Args Command arguments.
	Args *CommandArgs `form:"args,omitempty" json:"args,omitempty"`
}

// ExecuteAdbPullParams defines parameters for ExecuteAdbPull.
type ExecuteAdbPullParams struct {
	// Args Command arguments.
	Args CommandArgs `form:"args" json:"args"`
}

// ExecuteAdbPushParams defines parameters for ExecuteAdbPush.
type ExecuteAdbPushParams struct {
	// Args Command arguments.
	Args CommandArgs `form:"args" json:"args"`
}

// ExecuteAdbRebootParams defines parameters for ExecuteAdbReboot.
type ExecuteAdbRebootParams struct {
	// Args Command arguments.
	Args *RebootArgs `form:"args,omitempty" json:"args,omitempty"`
}

// ExecuteAdbShellParams defines parameters for ExecuteAdbShell.
type ExecuteAdbShellParams struct {
	// Args Command arguments.
	Args CommandArgs `form:"args" json:"args"`
}

// GetDevicesParams defines parameters for GetDevices.
type GetDevicesParams struct {
	// Interval Interval time for polling. (seconds) If omit or 0 then no polling. (1 shot)
	Interval *PollingInterval `form:"interval,omitempty" json:"interval,omitempty"`
}

// ExecuteAdbKillServerJSONRequestBody defines body for ExecuteAdbKillServer for application/json ContentType.
type ExecuteAdbKillServerJSONRequestBody = SerialList

// ExecuteAdbLogcatJSONRequestBody defines body for ExecuteAdbLogcat for application/json ContentType.
type ExecuteAdbLogcatJSONRequestBody = SerialList

// ExecuteAdbPullJSONRequestBody defines body for ExecuteAdbPull for application/json ContentType.
type ExecuteAdbPullJSONRequestBody = SerialList

// ExecuteAdbPushJSONRequestBody defines body for ExecuteAdbPush for application/json ContentType.
type ExecuteAdbPushJSONRequestBody = SerialList

// ExecuteAdbRebootJSONRequestBody defines body for ExecuteAdbReboot for application/json ContentType.
type ExecuteAdbRebootJSONRequestBody = SerialList

// ExecuteAdbRootJSONRequestBody defines body for ExecuteAdbRoot for application/json ContentType.
type ExecuteAdbRootJSONRequestBody = SerialList

// ExecuteAdbShellJSONRequestBody defines body for ExecuteAdbShell for application/json ContentType.
type ExecuteAdbShellJSONRequestBody = SerialList

// ExecuteAdbStartServerJSONRequestBody defines body for ExecuteAdbStartServer for application/json ContentType.
type ExecuteAdbStartServerJSONRequestBody = SerialList

// ExecuteAdbUnrootJSONRequestBody defines body for ExecuteAdbUnroot for application/json ContentType.
type ExecuteAdbUnrootJSONRequestBody = SerialList

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ExecuteAdbKillServer Execute adb kill-server command and report result.
	// (POST /api/adb/kill-server)
	ExecuteAdbKillServer(ctx echo.Context) error
	// ExecuteAdbLogcat Execute adb logcat command and report result.
	// (POST /api/adb/logcat)
	ExecuteAdbLogcat(ctx echo.Context, params ExecuteAdbLogcatParams) error
	// ExecuteAdbPull Execute adb pull command that pull file(s) and report result.
	// (POST /api/adb/pull)
	ExecuteAdbPull(ctx echo.Context, params ExecuteAdbPullParams) error
	// ExecuteAdbPush Execute adb push command that push file(s) and report result.
	// (POST /api/adb/push)
	ExecuteAdbPush(ctx echo.Context, params ExecuteAdbPushParams) error
	// ExecuteAdbReboot Execute adb reroot command and report result.
	// (POST /api/adb/reboot)
	ExecuteAdbReboot(ctx echo.Context, params ExecuteAdbRebootParams) error
	// ExecuteAdbRoot Execute adb root command and report result.
	// (POST /api/adb/root)
	ExecuteAdbRoot(ctx echo.Context) error
	// ExecuteAdbShell Execute adb shell command and report result.
	// (POST /api/adb/shell)
	ExecuteAdbShell(ctx echo.Context, params ExecuteAdbShellParams) error
	// ExecuteAdbStartServer Execute adb start-server command and report result.
	// (POST /api/adb/start-server)
	ExecuteAdbStartServer(ctx echo.Context) error
	// ExecuteAdbUnroot Execute adb unroot command and report result.
	// (POST /api/adb/unroot)
	ExecuteAdbUnroot(ctx echo.Context) error
	// GetDevices Execute adb devices command and report device status.
	// (GET /api/devices)
	GetDevices(ctx echo.Context, params GetDevicesParams) error
	// GetMainPage Get GUI
	// (GET /gui)
	GetMainPage(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ExecuteAdbKillServer converts echo context to params.
func (w *ServerInterfaceWrapper) ExecuteAdbKillServer(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ExecuteAdbKillServer(ctx)
	return err
}

// ExecuteAdbLogcat converts echo context to params.
func (w *ServerInterfaceWrapper) ExecuteAdbLogcat(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ExecuteAdbLogcatParams
	// ------------- Optional query parameter "args" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "args", ctx.QueryParams(), &params.Args, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter args: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ExecuteAdbLogcat(ctx, params)
	return err
}

// ExecuteAdbPull converts echo context to params.
func (w *ServerInterfaceWrapper) ExecuteAdbPull(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ExecuteAdbPullParams
	// ------------- Required query parameter "args" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, true, "args", ctx.QueryParams(), &params.Args, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter args: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ExecuteAdbPull(ctx, params)
	return err
}

// ExecuteAdbPush converts echo context to params.
func (w *ServerInterfaceWrapper) ExecuteAdbPush(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ExecuteAdbPushParams
	// ------------- Required query parameter "args" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, true, "args", ctx.QueryParams(), &params.Args, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter args: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ExecuteAdbPush(ctx, params)
	return err
}

// ExecuteAdbReboot converts echo context to params.
func (w *ServerInterfaceWrapper) ExecuteAdbReboot(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ExecuteAdbRebootParams
	// ------------- Optional query parameter "args" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "args", ctx.QueryParams(), &params.Args, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter args: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ExecuteAdbReboot(ctx, params)
	return err
}

// ExecuteAdbRoot converts echo context to params.
func (w *ServerInterfaceWrapper) ExecuteAdbRoot(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ExecuteAdbRoot(ctx)
	return err
}

// ExecuteAdbShell converts echo context to params.
func (w *ServerInterfaceWrapper) ExecuteAdbShell(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ExecuteAdbShellParams
	// ------------- Required query parameter "args" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, true, "args", ctx.QueryParams(), &params.Args, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter args: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ExecuteAdbShell(ctx, params)
	return err
}

// ExecuteAdbStartServer converts echo context to params.
func (w *ServerInterfaceWrapper) ExecuteAdbStartServer(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ExecuteAdbStartServer(ctx)
	return err
}

// ExecuteAdbUnroot converts echo context to params.
func (w *ServerInterfaceWrapper) ExecuteAdbUnroot(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ExecuteAdbUnroot(ctx)
	return err
}

// GetDevices converts echo context to params.
func (w *ServerInterfaceWrapper) GetDevices(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDevicesParams
	// ------------- Optional query parameter "interval" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "interval", ctx.QueryParams(), &params.Interval, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter interval: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDevices(ctx, params)
	return err
}

// GetMainPage converts echo context to params.
func (w *ServerInterfaceWrapper) GetMainPage(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMainPage(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/gui", wrapper.GetMainPage, options.OperationMiddlewares["GetMainPage"]...)
	router.GET(options.BaseURL+"/api/devices", wrapper.GetDevices, options.OperationMiddlewares["GetDevices"]...)
	router.POST(options.BaseURL+"/api/adb/push", wrapper.ExecuteAdbPush, options.OperationMiddlewares["ExecuteAdbPush"]...)
	router.POST(options.BaseURL+"/api/adb/pull", wrapper.ExecuteAdbPull, options.OperationMiddlewares["ExecuteAdbPull"]...)
	router.POST(options.BaseURL+"/api/adb/shell", wrapper.ExecuteAdbShell, options.OperationMiddlewares["ExecuteAdbShell"]...)
	router.POST(options.BaseURL+"/api/adb/logcat", wrapper.ExecuteAdbLogcat, options.OperationMiddlewares["ExecuteAdbLogcat"]...)
	router.POST(options.BaseURL+"/api/adb/reboot", wrapper.ExecuteAdbReboot, options.OperationMiddlewares["ExecuteAdbReboot"]...)
	router.POST(options.BaseURL+"/api/adb/root", wrapper.ExecuteAdbRoot, options.OperationMiddlewares["ExecuteAdbRoot"]...)
	router.POST(options.BaseURL+"/api/adb/unroot", wrapper.ExecuteAdbUnroot, options.OperationMiddlewares["ExecuteAdbUnroot"]...)
	router.POST(options.BaseURL+"/api/adb/start-server", wrapper.ExecuteAdbStartServer, options.OperationMiddlewares["ExecuteAdbStartServer"]...)
	router.POST(options.BaseURL+"/api/adb/kill-server", wrapper.ExecuteAdbKillServer, options.OperationMiddlewares["ExecuteAdbKillServer"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fptb9u+Ef8qBLfgnwCy7LjJEBgYisR5gNeHGXEKDCj6gpbOEluKVEnKjRvkuw9HyrZky4nbZUaLGn5j",
	"ieQ98fe7O0p6oJHKciVBWkN7DzRnmmVgQburvsoyJuNznbjLGEykeW65krRH33JjiZqQyE8iTCdFhnJC",
	"GlC4Z1kugPYo04n5Z0sGJ8FZ6H5uNBcqBtqbMGEgoBzlfS1Az2hAJcvm62hATZRCxlD73zVMaI/+rb20",
	"uO1HTbtq6GNAjZ053ROlM7weKiG4TAbSgp4yse7LfIRYngGZKE1yvyQkhwYiJWNzRAYTojJuidKkQ2wK",
	"kkhVmXdMTKrsUdX504qrVhcbPOVzs6reZlzyrMhorxNQO8vn8xLQ6w4+BlTD1wKMvVAxB7dXd0wnYHGP",
	"8CpS0oJ0f1meCx4xdLz92aD3D1sGeQSaM+FEPqLOp+FgnQGIBbSNa4h9DLy1JlfSeEtHo6vb8nrFVAv3",
	"tg1TkLZlrAaW1W2t6x+NrkgGxrAEQnIYM8vIWMUzwg351+jf73FTM1bfHoqzeuQhDMNHugizsZrLpMnF",
	"uZkEdZUWBTQFFs/5wqIUWn0lrVbiKWOHWqV8zC2JmEmBcEnGWn0zoAmTcVtpokGwGTGgp6DrfJKqFaGa",
	"BoMD2ldSQuSVbNb+BiAn0WJqXf4XgLzFBJ9u1IDb07pzI5t1VOc5Qo1GVzU965vbpO4/rfMoAtG6KCYT",
	"cHef0HnJDRsLIHN4kfF8FUY41+p+FpJD5aYfrQS1af/RgBL8z2bDflMW5BYyN3dF9EIX05rNqAurW34L",
	"phB2s3Ttxsk3blMEB2cC1eRa5aBtyXy9kLH0bzh4f0PK/EsOyz9H5PQfh2cnR2Q8s2CQu8iHcD0SAfW6",
	"nksQlzDlEfg0schKnvkf5yKCuX2fFmrU+DNEdi0KW5QcL6oe6i3KRBnlhm3wHgzkRDWgC6Y8Rq76TFIS",
	"px772K2vx/7169dNIc1UDA2V6B3eJlgZ3IY4eXWCDvk9iNZxp0lorlVcRLYx4eDAk4I3GPoze48VitnC",
	"bLnKz8X94PG67XeaSZMrbcngsmbx8Xpp3AS60pwm0Hkb5pWyGXA+XMYTbwUBWyGvAqyNsBstAl03wjux",
	"adfOL/rH3VeXV9dNe1eL73rJdPdXBEtsOj5SJQWXWALUZFL+KyQrbKo0/w6xu/wi1TeJMV1as1i2ZspQ",
	"q7GA7BIs48I00csNuFoBWrsa6NN4E81w7rqMK7du3gXUwvTXRKm/sBmQyhINkUok+kGYIUwS14JJDLIm",
	"cF/+L7NMQFC1Kyy5VolmGc4aMxulZMIFNCfMp0Meqbhu32mnsc+z3ApYl3ILLJ4UgmANdQEzG8T6xhad",
	"GblWgrgINVbaNV7cwlgp21zt5lWOCCQIWsDiMdFuRRVFeC0U9kcu8Udq6jtfw2PA+5W/LVZY1fIiKjxd",
	"hrTSfj7D00pp/AFyLnNXxuVbkIlNqymmJCuGijfWh7uUGwQYk+R8OCCxilyIXJ5wITq/vMCuyygBlc6u",
	"3GKKo/1y9Hw4oAGdgjZe9HHYCTtomcpBspzTHn0VdsITJAazqXOwzXLeZvG4/YUL0fLy3YlOmc0NRVlp",
	"0ezCQOzMdK0zJjouXaNbpaFjAooYxEi3e4gKC+fx+A0XwiOMVs8is02Rrx1X2pWzyurhoNvpbJZRzmtX",
	"TxCPAT3xa17kzLOStRoOBRcsJrfenRC1n+5UeyO/Q0doU2QZ07PlPjmOVtCxPLm7VspVWN9ReQELRAmV",
	"RMzuDExvvbqg9jDi41YN98pjh8FBt/9duXq020cOn/Ys+KVZ4BG9NQHyQoidwX+Iyl4A/AfdaxNHTMcH",
	"3eucR7bQcGDcjDCXyY9Rov4IZ0+RP4AiiPnlw7yUWX8HO95Dc7QFZUy6Q8qY9CUoEysTIW0WLDno9pto",
	"1L3e02dPn2foY9JV+ph0a/qU56BdEcif9f5HCtUOey/eb1WOo3sy/GZk0KCV2r7d0juFvgf+Hj+/Mn5+",
	"BD0mhR126yOn7QV6j5y7dqMlD7r9k4Nu/6felu8bjT+OGw7u25PDMm13/XRwhEr3jwd/CzRV8LE1qAq5",
	"04r9wavbI+mXRpIHxVYYKt+uopEJ2OY37/4N7WbsXD2FnRuwl6WOtUrdFJbllPbqp2O+Hu6B8/8Dzvxd",
	"ewNy5q/33NvOEkBJwTcC5wYsyRiXJGeJ++yh8gquESXvGJdDlgBt3uTVb9NSm6185rXFN2S20PIJq+qB",
	"QQ9uPgy8JJ+WmxrMGCasEJgTCy1oj6bW5qbXbgsVMZEqY3tnnbMOffz0+N8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
