name: Build

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache: true

      - name: Generate Self-Signed Certificates
        run: |
          openssl req -x509 -newkey rsa:2048 -nodes \
            -keyout internal/infra/server/assets/key.pem \
            -out internal/infra/server/assets/cert.pem \
            -days 1 \
            -subj "/CN=localhost" \
            -addext "subjectAltName=DNS:localhost,IP:127.0.0.1"

      - name: Install dependencies & Build
        run: |
          go mod download
          go build -v ./...